### ISSUE TITLE
[Android] AutoPlay functionality is broken in 3.0.0

### ISSUE THREAD

**Issue by adrianknight89** [martijn00/LottieXamarin#234]
### Old (and correct) behavior

Animation auto plays when ListView is refreshed.

### Current behavior

If you place a Lottie animation in a Xamarin Forms ListView cell and refresh the list with a swipe gesture, AutoPlay (now IsPlaying) no longer works. The animation is paused. This issue does not exist on iOS. Reverting back to 2.7.1 fixes the issue.

Not sure if #206 has anything to do with this.

### Configuration

**Version:** 3.0.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Can you open a PR to fix this?

**Comment by adrianknight89** [comment]
@martijn00 Can you tell me the last commit id that got included in 2.7.1? I don't see a tag for that build.

Also, can you give me instructions to build a Nuget? I tried running cake with `.\build.ps1`, but it gets stuck after the `Running build script` message.

**Comment by martijn00** [comment]
I'm not totally sure which commit id that is. It's easy to build a nuget. Just run in release mode from command line or VS2019. I'll add support for vs4mac soon too.

**Comment by adrianknight89** [comment]
It doesn't seem to be building for me. I'm running VS2019 16.2 and get the error described here:

https://github.com/xamarin/xamarin-android/issues/3423

**Comment by martijn00** [comment]
I've fixed some stuff and released an update

**Comment by adrianknight89** [comment]
I just tested 3.0.1. The issue still exists. Here's a repro:

[App165.zip](https://github.com/martijn00/LottieXamarin/files/3567332/App165.zip)

When you refresh the ListView, animation stops. Can we re-open this?
